"""initial migration

Revision ID: b8453823d541
Revises: 
Create Date: 2025-12-07 18:40:00.626441

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8453823d541'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Rasy',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nazwa', sa.String(length=50), nullable=False),
    sa.Column('nr_fci', sa.Integer(), nullable=True),
    sa.Column('charakter', sa.Text(), nullable=False),
    sa.Column('proby_pracy', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nazwa')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Rasy')
    # ### end Alembic commands ###
